name: Task
description: "Simple sets of actions"
title: "Task: "
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      Task issues serve to manage and track simple sets of actions. They are managed by one assignee who organizes, documents, tracks and closes the task.
# Task description
- type: textarea
  attributes:
    label: Task description
    description: Clearly describe the 'why', 'how' and 'what' of the task. To facilitate working with related documents, put a GitHub hyperlink to the concerned folder and external URLs. You can also drop images or other material necessary here directly. 
    placeholder: |
      This task serves to ...
# Task ressources
- type: textarea
  attributes:
    label: Task resources
    description:  Clearly list all the resources associated with this task (file URL, hyperlinks, contacts, etc.)
    placeholder: |
      - URLs
      
# List of actions
- type: textarea
  attributes:
    label: List of actions
    description: |
      List actions required to complete the task. Actions can be listed then created as issues and assigned to others.
    value: |
      - [ ] Action: ...

  # Check list
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Task issue checklist
      description: To complete before putting in “Ready”
      options:
        - label: Name the task clearly by stating what will be achieved using an action verb
        - label: Assign **one** person. The task assignee is responsible to coordinate listed actions and deliver the task on time
        - label: Add to relevant projects
        - label: Link back to parent issue (e.g. Epic)
        - label: Complete _Task description_ section
        - label: Complete _Task resources_ section
        - label: Complete _List of actions_ section
