name: Hire research assistants
description: "Steps to hire a new collaborator or extend contracts"
title: "Hire: [student name] as [position] for [mission] in [semester]"
assignees:
  - delphineduplain
projects:
  - "CUPUM/145"
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      # General

      This issue template serves to create hiring of students at the UNESCO Chair in Urban Landscape

- type: input
  id: contact
  attributes:
    label: Hiree contact issue URL
    description: Plase copy-paste from [contact project](https://github.com/orgs/CUPUM/projects/179/views/1)
  validations:
    required: true

- type: input
  id: start_date
  attributes:
    label: Start date
    description: First day of work
  validations:
    required: true

- type: input
  id: end_date
  attributes:
    label: End date
    description: Last day of work
  validations:
    required: true

- type: dropdown
  id: position
  attributes:
    label: Hirement position
    options:
      - Research assistant
      - Teaching assistant
      - Technical assistant
      - Other
  validations:
    required: true

- type: input
  id: mission
  attributes:
    label: Mission
    description: What project/function will the hiree work on 
  validations:
    required: true

- type: input
  id: funds
  attributes:
    label: Financial project number
    description: Plase copy-paste from [funding management project](https://github.com/orgs/CUPUM/projects/140/views/1)
  validations:
    required: false

- type: dropdown
  id: days
  attributes:
    label: Which days of the week will the hiree work
    options:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday
    multiple: true
  validations:
    required: true

- type: input
  id: hours
  attributes:
    label: Hours of contract
    description: How many hours will be worked/paid
  validations:
    required: true

# Responsabilities and KPIs outline
- type: textarea
  id: scope
  attributes:
    label: Statement of work
    value: |
      | Tâche           | Indicateur clé | Taux |
      |-----------------|--------------  |------|
      | Describe task 1 | KPI 1          | XX%  |
      | Describe task 1 | KPI 2          | 75%  |
    render: bash
    
# List of actions
- type: checkboxes
  id: action-pre
  attributes:
    label: Preliminary steps for 35h+ new contract
    description: Please complete in order
    options:
      - label: "Task: Email Department job posting"
      - label: "Task: Select hiree from candidacies"

- type: checkboxes
  id: action-post
  attributes:
    label: Sub-issues
    description: Check off or convert to sub-issues if needed
    options:
      - label: "Task: Email hiree statement of work"
      - label: "Task: Email Department hiree contract details"
      - label: "Task: Add hiring issue URL to hiree contact issue"
