name: Hire research assistants
description: "Steps to hire a new collaborator or extend contracts"
title: "Hire: [student name] as research assistant for [Project name] for [semester]"
assignees:
  - delphineduplain
projects:
  - "CUPUM/145"
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      Give an adequate title to your hiring issue.
      - Specify the student's name
      - Specify the semester, example: `A25` for _automne 2025_

# Details of hiree and employment
- type: textarea
  attributes:
    label: Hiring details
    value: |
      - Last name:
      - First name:
      - Email (new assistant only):
      - Study cycle (new assistant only):
      - Program (new assistant only):
      - Start date:
      - End date:
      - Project name: 
      - Financial project code:
      - Total number of hours:
      - Work days:
        - [ ] Monday
        - [ ] Tuesday
        - [ ] Wednesday
        - [ ] Thursday
        - [ ] Friday

# Responsabilities and KPIs outline
- type: textarea
  attributes:
    label: Statement of work
    value: |
      | Task | Key Performance Indicator | Percentage |
      | :--    | :--        | :--            |
      | Apply for funding | 5000$ | 25% |
      | Recruit participants | 29 participants | 75% |

# List of actions
- type: checkboxes
  id: action-pre
  attributes:
    label: Preliminary steps for 35h+ new contract
    description: Please complete in order
    options:
      - label: Fill URBAPA job posting form
      - label: Email form to I. Couillard for posting
      - label: Receive applications
      - label: Evaluate applications
      - label: Confirm position to the choosen candidate

- type: checkboxes
  id: action-post
  attributes:
    label: Sub-issues
    description: Check off or convert to sub-issues if needed
    options:
      - label: "Task: Output statement of work"
      - label: "Task: Create entry on koseki-log-studetns_contract.xlxs"
      - label: "Task: Email I. Couillard with log entry for contract creation"
      - label: "Task: Email [Student name] with statement of work"
