name: Publication
description: "Manages the instigation, wirting, publishing and archiving of publications."
title: "Publication: [Type] “[Title]” published in/by *[Publication/Publisher]*"
assignees: ["sjinko"]
projects: ["CUPUM/143"]
body:

# Guidelines
body:
- type: markdown
  attributes:
    value: |
    Publications are managed as Epic issues containting non-epic sub-issues (tasks, meeting, workshop, etc). They follow an output oriented life cycle process:
    1. Proposal / Call submission (define the gist and framwork)
    2. Publication notes (planning and research)
    3. Output of material (supporting figures, tables, etc.)
    4. Drafting of manuscript (writing it down)
    5. Submission (putting things together nicely)
    6. Review (responding to comments from publisher)
    7. Publishing (archiving published and non-published material)
    For all practical matters, we follow the [APA Style](https://apastyle.apa.org), unless instructed otherwise by the publisher.

body:
- type: input
  id: prevalence
  attributes:
    label: Bug prevalence
    description: "How often do you or others encounter this bug?"
    placeholder: "Whenever I visit the user account page (1-2 times a week)"
  validations:
    required: true
    


    
