name: Publication
description: "Manages the instigation, writing, publishing and archiving of publications."
title: "Publication: [Type] “[Title]” published in/by *[Pub. Name]*"
assignees: []
projects: ["CUPUM/143"]
body:

- type: markdown
  attributes:
    value: |
      ## Overview
      Publications are managed as an Epic issues containing non-epic sub-issues (tasks, meetings, workshops, etc.). They should be created/transferred within the Publication repo and follow an output oriented life cycle process:
      1. Proposal / Call submission (define the gist and framework)
      2. Publication notes (planning and research)
      3. Output of material (supporting figures, tables, etc.)
      4. Drafting of the manuscript (writing it down)
      5. Submission (putting things together nicely)
      6. Review (responding to comments from publisher)
      7. Publishing (archiving published and non-published material)
      For all practical matters, we follow the [APA Style](https://apastyle.apa.org), unless instructed otherwise by the publisher.

- type: dropdown
  id: type
  attributes:
    label: What type of publication is it?
    options:
      - Books
      - Brochures
      - Book chapters
      - Journal articles (peer-reviewed)
      - Conference proceedings (peer-reviewed)
      - Conference abstract (peer-reviewed)
      - Conference posters (peer-reviewed)
      - Journal contributions (non-peer reviewed, e.g., book review, introduction or commentary)
      - News and editorial articles (including official blogs)
      - Exhibition
      - Videos
      - Inventions
      - Application and software
      - Algorithmic models
      - Data sets
      - Reports
      - Theses
      - Presentations
      - Other formats
  validations:
    required: true

- type: input
  id: title
  attributes:
    label: Publication title
    description: "What is the title of the publication?"
    placeholder: "Short and impactful title that summarize the gist"
  validations:
    required: true

- type: input
  id: pub_name
  attributes:
    label: Publication or Publisher Name (Pub. Name)
    description: "Journal, edited book, conference, event, website or publisher's name (for books)"
    placeholder: "e.g. 'Science' or 'Oxford Handbook of Research'"
  validations:
    required: true

- type: textarea
  id: authors
  attributes:
    label: Author(s) of the publication
    description: List authors as [Contact](https://github.com/orgs/CUPUM/projects/179) issue URL
    value: |
      - https://github.com/CUPUM/...
      - https://github.com/CUPUM/...
      - https://github.com/CUPUM/...
      ...
  validations:
    required: true

- type: textarea
  id: funding
  attributes:
    label: Name of funding(s) supporting this publication
    description: List funding as [Subvention management](https://github.com/orgs/CUPUM/projects/140) issue
    value: |
      - https://github.com/CUPUM/...
      - https://github.com/CUPUM/...
      - https://github.com/CUPUM/...
      ...
  validations:
    required: false

- type: checkboxes
  id: issue-actions
  attributes:
    label: Issue checklist
    description: To create the issue, make sure to ... 
    options:
      - label: "Action: Create or transfer the issue within the repo **Publications/**"
      - label: "Action: Name the issue according to guidelines"
      - label: "Action: Add the issue to the project **@sjinko: Publications** (automatic)"
      - label: "Action: Add the issue to other associated projects (e.g., research / teaching projects)"
      - label: "Action: Add project metadata (starting / end date)"
      - label: "Action: List sub-issues tasks, meetings, workshops required"
      - label: "Action: Comment current issue with co-authors' GitHub handles"
      - label: "Action: Create publication project directory in the **Publication/** repo"

- type: textarea
  id: context
  attributes:
    label: Context of the publication
    description: In which context is this publication produced ?
    value: |
      This publication results from ...
  validations:
    required: true

- type: textarea
  id: objectives
  attributes:
    label: Objectives of the publication
    description: Explain why the publication is made.
    value: |
      This publication aims to ...
  validations:
    required: true

- type: textarea
  id: resources
  attributes:
    label: Resources of the publication
    description: Where are the resources linked to this publication
    value: |
      - URL link to GitHub project folder on Publication/ repo: 
      - URL link to call: 
  validations:
    required: true

- type: checkboxes
  id: subissues
  attributes:
    label: List of subissues
    description: List of all tasks, meetings, workshop required (to convert to subissues)
    options:
      - label: "Task: Submit abstract for [Title] to [Call Name] by [Call Deadline]"
      - label: "Task: Complete publication notes for [Title]"
      - label: "Task: Output of material for [Title]"
      - label: "Task: Draft manuscript for [Title]"
      - label: "Task: Submit [Title] to [Call Name] by [Submission Deadline]"
      - label: "Task: Review [Title] to [Call Name] by [Review Deadline]"
      - label: "Task: Add [Title] to CUPUM's Zotero group (in publications coll.)"
      - label: "Task: Archive [Title] on repo *Publication*"
      - label: "Task: Archive [Title] on a public repository (Arxiv or SocArxiv)"
