name: Key Attribution
description: "Manage the attribution, tracking, and return of keys for new collaborators and guests."
title: "Key Attribution: "
projects: "github/33"
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      This template manages the attribution of keys to new collaborators, including request, registration, tracking, and return processes. Each key has a unique identifying code that must be registered and tracked in the key log. Key can be borrowed in exchange of a caution deposit. Please fill all required fields (*).
