name: Key Attribution
description: "Manage the attribution, tracking, and return of keys for new collaborators and guests."
title: "Key Attribution: "
projects: "github/33"
body:


# Lost of the key
- type: textarea
  attributes:
    label: Lost of Key
    description: Enter a detailed account of the losing, stealing, breaking or destructing of the borrowed key.
    placeholder: |
      Detailed account of the events ...

body:
- type: checkboxes
  attributes:
    label: Actions
    description: Check completed actions
    options:
      - label: Action — Request key to Key master
      - label: Action — Pay caution to Caution holder
      - label: Action — Receive key from Key master
      - label: Action — Return key to Key master
      - label: Action — Receive caution from Caution holder
