name: News
description: "Communication template (for single posts or weekly campaigns)."
title: "News: [Story short title] featuring [Subject] by [Deadline]"
assignees: ["sjinko"]
projects: ["CUPUM/5"]
body:

  - type: markdown
    attributes:
      value: |
        ## General

        This template manages news announcements made by the UNESCO Chair in Urban Landscape. This concerns news published on the UNESCO Chair’s website and social media, as well as those published by our partners.
        News publications follow the Chair’s communication strategy and require active engagement from the person at the origin of the news.

  - type: input
    id: deadline
    attributes:
      label: Publication deadline
      description: "Date by which this story should be published (YYYY-MM-DD)"
      placeholder: "2026-09-19"
    validations:
      required: true

  - type: input
    id: story-title-en
    attributes:
      label: Story title in English
      description: "Short original catchy title focused on Chairmember"
    validations:
      required: true

  - type: textarea
    id: story-en
    attributes:
      label: Story caption in English
      description: "Three-paragraph impactful story based on facts and quotes"
      render: bash
      value: |
        Paragraph 1: Hook - who, what, why this matters.
        Paragraph 2: Details - facts, context, quotes.
        Paragraph 3: Impact - outcomes, next steps, call to action.
    validations:
      required: true

  - type: input
    id: hashtag-en
    attributes:
      label: Hashtags in English
      description: "List four hashtags related to story, two common, two specific"
      placeholder: "#UrbanLandscape #UNESCOChair #YourSpecificTag #AnotherSpecificTag"
    validations:
      required: true

  - type: input
    id: story-title-fr
    attributes:
      label: Story title in French
      description: "Short original catchy title focused on Chairmember"
    validations:
      required: true

  - type: textarea
    id: story-fr
    attributes:
      label: Story caption in French
      description: "Three-paragraph impactful story based on facts and quotes"
      render: bash
      value: |
        Paragraphe 1: Accroche - qui, quoi, pourquoi c'est important.
        Paragraphe 2: Détails - faits, contexte, citations.
        Paragraphe 3: Impact - résultats, prochaines étapes, appel à l'action.
    validations:
      required: true

  - type: input
    id: hashtag-fr
    attributes:
      label: Hashtags in French
      description: "List four hashtags related to story, two common, two specific"
      placeholder: "#PaysageUrbain #ChaireUNESCO #VotreMotClicSpecifique #AutreMotClicSpecifique"
    validations:
      required: true

  - type: textarea
    id: subjects-externals
    attributes:
      label: News subjects
      description: List all subjects (persons or organizations) mentioned in the story.
      placeholder: |
        - UNESCO Chair in Urban Landscape
        - Name of person or organization 1
        - Name of person or organization 2
        - Name of person or organization 3
    validations:
      required: true

  - type: checkboxes
    id: checklist-news_content
    attributes:
      label: Checklist
      description: Make sure this has been done
      options:
        - label: 'Action: <a href="https://gist.github.com/sjinko/6718034d2d7d827eca8575d62e9d9fea" target="_blank">Get authorization from mentioned individuals for media dissemination</a>'
        - label: "Action: Clearly mention funding and support if any"
        - label: "Action: List necessary @ tags (School, Faculty, University, Venue, External subjects, Funding agency, Support organizations, etc.)"
        - label: "Action: Proofread content using ChatGPT or Claude"
        - label: "Action: Check on media diffusion form responses if all invidiuals mentioned in the story have approved to be featured in the story and on social media"

  - type: checkboxes
    id: subissues-subject
    attributes:
      label: Media files
      description: "Collect or produce media files (pictures, short films) for the story."
      options:
        - label: "Action: Drop cover pictures in issue comments"
        - label: "Action: Drop short interview reel (vertical) in issue comments"

  - type: checkboxes
    id: subissues-manager
    attributes:
      label: Publish
      description: Publish prepared material on the Chair’s website and social media channels.
      options:
        - label: "Action: Publish news in French on Facebook and add to story"
        - label: "Action: Publish news in English on UNESCO Chair website"
        - label: "Action: Publish news in English on Instagram and add to story"
        - label: "Action: Publish news in English on LinkedIn"  
        - label: "Action: Publish reel on IG and FB"

  - type: checkboxes
    id: subissues-diffusion
    attributes:
      label: Ask chairholder if diffusion is needed
      description: Complete after validating with Chairholder
      options:
        - label: "Action: Email story material to Faculty communication team"
        - label: "Action: Email story material to University social media team"
        - label: "Task: Submit material to UdeM TV team"
