name: News
description: "Communication template (for single posts or weekly campaigns)."
title: "News: [Type] [Story] featuring [Subject] by [Deadline]"
assignees: ["roxanekasprzyk"]
projects: ["CUPUM/5"]
body:

  - type: markdown
    attributes:
      value: |
        ## General

        This template manages news announcement made by the UNESCO Chair in Urban Landscape. This concerns news published on the UNESCO Chair’s website and social media and those published by our partners.
        News publication follow the chair’s communication strategy and require an active engagement from the person at the origin of the news.
        
        There are two types of news:
        
        1. Announcement (inform of upcoming story, e.g. announcing an upcoming event)
        2. Coverage (inform of an ongoing or past story, e.g. covering a new publication or award)

        News include, but is not limited to:
        
        - Arrival of new UNESCO Chair member
        - Participation in scientific, academic or public events
        - Publications, exhibitions and other forms of research dissemination
        - Awarded honour, prize, scholarship, funding, etc
        - Event or activity organized by the UNESCO Chair
        - Social activities and other miscellaneous news

       ## Roles

       The publication of news includes the following roles:
       - Subject: The chair member(s) at the center of the news
       - Communication manager: The person managing and curating the news
       - Chair holder: Shin Koseki

  - type: markdown
     attributes:
     value: |
       ## Phase 1 — Preparation by subject

       This first phase must be completed by the subject (chair member) featured in the story. Subject should refer to Communication manager for help and support if needed.

  - type: checkboxes
    id: checklist-subject
    attributes:
      label: Check list
      description: Make sure this has been done first
      options:
        - label: Name the news issues following the proposed structure
        - label: Assign news subject(s) to issue
        - label: Confirm with External subjects (collaborating persons or organizations) they agree to be mentionned
        - label: Proofread content using Antidote

  - type: input
    id: story-title-en
    attributes:
      label: Story title in English
      description: "Short original cachy title focus on subject"

  - type: textarea
    id: story-en
    attributes:
      label: Story caption in English
      description: "Three paragraph impactful story (ask ChatGPT if needed)"

  - type: input
    id: hastag-en
    attributes:
      label: Hashtags in English
      description: "List four hashtags related to story, two common, two specific"

  - type: input
    id: story-title-en
    attributes:
      label: Story title in English
      description: "Short original cachy title focus on subject"
  
  - type: textarea
    id: story-fr
    attributes:
      label: Story caption in French
      description: "Three paragraph impactful story (ask ChatGPT if needed)"
  
  - type: input
    id: hastag-fr
    attributes:
      label: Hashtags in French
      description: "List four hashtags related to story, two common, two specific"

  - type: textarea
    id: subjects-externals
    attributes:
      label: External subjects
      description: List all external subjects (persons or organizations) mentioned in the story (add URL from Contacts issues if present).   
        
  - type: checkboxes
    id: subissues-subject
    attributes:
      label: Subject sub-issues
      description: Activate as sub-issues and complete
      options:
        - label: "Task: Send communication manager with a cover and closing pictures of the story (use Slack > team-communication)"
        - label: "Task: Send communication manager with self made pictures and short films (vertical) during preparation and unfolding of the story (use Slack > team-communication)"

  - type: markdown
    attributes:
    value: |
      ## Phase 2 — Publication by the communcation manager
      
      Use templates provided in Communication/template/ accordingly:
      
        - Instagram: In English without UNESCO Chair sticker
        - LinkedIn: In English with square template and UNESCO Chair sticker
        - Facebook: In French with square template and UNESCO Chair sticker
        - Website: In English without UNESCO Chair sticker

  - type: checkboxes
    id: checklist-subject
    attributes:
      label: Check list
      description: Make sure this has been done first
      options:
        - label: Proofread content using Antidote
        - label: Clearly mention Benefactors if any
        - label: Tag School, Faculty, University, Venue, External subjects and Benefactors

   - type: input
     id: presskit
     attributes:
       label: Press kit folder
       description: "URL to presskit foler on Communication repo"
       placeholder: "https://github.com/CUPUM/communication/tree/main/visuals/<yyyymmdd-story_subtitle/>"

   - type: checkboxes
     id: subissues-manager
     attributes:
       label: Communication manager sub-issues
       description: Activate as sub-issues and complete
       options:
         - label: "Task: Publish cover story and picture on UNESCO Chair website"
         - label: "Task: Publish cover story and picture on IG, FB, LK post using templates"
         - label: "Task: Publish self made pictures and short films as “story” on IG and FB post"
         - label: "Task: Publish closing story on IG and FB post using templates"
         - label: "Task: Ask Chair holder to send story material to Faculty communication team"
