name: News
description: "Communication template (for single posts or weekly campaigns)."
title: "News: [Type] [Story] featuring [Subject] by [Deadline]"
assignees: ["roxanekasprzyk"]
projects: ["CUPUM/5"]
body:

  - type: markdown
    attributes:
      value: |
        ## General

        This template manages news announcement made by the UNESCO Chair in Urban Landscape. This concerns news published on the UNESCO Chair’s website and social media and those published by our partners.
        News publication follow the chair’s communication strategy and require an active engagement from the person at the origin of the news.
        
        There are two types of news:
        
        1. Announcement (inform of upcoming story, e.g. announcing an upcoming event)
        2. Coverage (inform of an ongoing or past story, e.g. covering a new publication or award)

        News include, but is not limited to:
        
        - Arrival of new UNESCO Chair member
        - Participation in scientific, academic or public events
        - Publications, exhibitions and other forms of research dissemination
        - Awarded honour, prize, scholarship, funding, etc
        - Event or activity organized by the UNESCO Chair
        - Social activities and other miscellaneous news

       ## Roles

       The publication of news includes the following roles:
       - Subject: The chair member(s) at the center of the news
       - Communication manager: The person managing and curating the news
       - Chair holder: Shin Koseki

  - type: checkboxes
    id: checklist
    attributes:
      label: Check list
      description: Make sure this has been done first
      options:
        - label: Name the news issues following the proposed structure
        - label: Assign news subject(s) to issue
        - label: Confirm with External subjects (collaborating persons or organizations) they agree to be mentionned
        - label: Proofread content using Antidote
        - label: Clearly mention Benefactors if any
        - label: Tag School, Faculty, University, Venue, External subjects and Benefactors

  - type: markdown
     attributes:
     value: |
       ## Phase 1 — Preparation by subject

       This first phase must be completed by the subject (chair member) featured in the story. Subject should refer to Communication manager for help and support if needed.

  - type: input
    id: story-title-en
    attributes:
      label: Story title in English
      description: "Short original cachy title focus on subject"

  - type: textarea
    id: story-en
    attributes:
      label: Story in English
      description: "Three paragraph impactful story (ask ChatGPT if needed)"

  - type: input
    id: hastag-en
    attributes:
      label: Hashtags in English
      description: "List four hashtags related to story, two common, two specific"

  - type: input
    id: story-title-en
    attributes:
      label: Story title in English
      description: "Short original cachy title focus on subject"
  
  - type: textarea
    id: story-fr
    attributes:
      label: Story in French
      description: "Three paragraph impactful story (ask ChatGPT if needed)"
  
  - type: input
    id: hastag-fr
    attributes:
      label: Hashtags in French
      description: "List four hashtags related to story, two common, two specific"

  - type: textarea
    id: subjects-externals
    attributes:
      label: External subjects
      description: List all external subjects (persons or organizations) mentioned in the story (add URL from Contacts issues if present).   
        
   - type: checkboxes
     id: subissues-subject
     attributes:
       label: Subject sub-issues
       description: Activate as sub-issues and complete
       options:
         - label: "Task: Send communication manager with a cover picture of the story (use Slack > team-communication)"
         - label: "Task: Send communication manager with self made pictures and short films (vertical) during preparation and unfolding of the story (use Slack > team-communication)"

   - type: markdown
     attributes:
     value: |
       ## Phase 2 — Publication by the communcation manager

   - type: input
     id: presskit
     attributes:
       label: Press kit folder
       description: ""

   - type: checkboxes
     id: subissues-manager
     attributes:
       label: Communication manager sub-issues
       description: Activate as sub-issues and complete
       options:
         - label: "Task: Publish story on IG, FB, LK post using templates"
         - label: "Task: Publish story on UNESCO Chair website"








  - type: textarea
    attributes:
      label: Description du projet
      description: Ajoutez un sommaire du projet concerné pour contextualiser la campagne de communication. 

  - type: textarea
    attributes:
      label: Création du presskit
      value: |
        - [ ] Action: Créer un dossier [ici](https://github.com/CUPUM/communication/tree/main/press_kits) selon cette nomenclature : aaaammjj-press_kit-noms-news_title
        - [ ] Action: Créer le communiqué de presse en FR selon le [template](https://github.com/CUPUM/communication/blob/main/templates/press_release/wulff-template-press_release_fr-20211228.docx) ou en EN selon le [template](https://github.com/CUPUM/communication/blob/main/templates/press_release/wulff-template-press_release_en-20211228.docx) et le déposer dans le dossier
        - [ ] Action: Tag @sjinko pour valider le communiqué
        - [ ] Action: Tranduire le communiqué (FR > EN ou EN > FR)
        - [ ] Action: Mettre les communiquées (FR et EN) en ligne sur le site web
        - [ ] Action: Commenter '@sjinko, à qui envoyer ce communiqué?' 

  - type: textarea
    attributes:
      label: Types de publications
      description: "Pour une campagne : Min 3 posts - Max 5 posts."
      value: |
        > Pour une campagne : Min 3 posts - Max 5 posts.
        - [ ] News 
        - [ ] Photo
        - [ ] Vidéo
        - [ ] Quote
        - [ ] Conférence

  - type: textarea
    attributes:
      label: Production des visuels
      value: |
        > Des images gratuites et libres de droit se trouvent [içi](https://unsplash.com)  
        > La charte graphique de la chaire se trouve [içi](https://github.com/CUPUM/communication/blob/main/templates/CHAIRE_UNESCO_PaysageUrbain_chartegraphique.pdf)

        - [ ] Créer un dossier [ici](https://github.com/CUPUM/communication/tree/main/visuals) selon cette nomenclature : aaaammjj-projet
        - [ ] Produire le(s) visuels en anglais selon le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post) adapté 
        - [ ] Produire le(s) visuels en français selon le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post) adapté 
        - [ ] Déposer le(s) visuel(s) dans le dossier selon la nomenclature : nom-projet-aaaammjj

  - type: textarea
    attributes:
      label: Production des _captions_
      value: |
        - [ ] Créer un texte pour le(s) visuel(s) à partir du presskit en utilisant le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post)
        - [ ] Ajouter les hashtags à la caption (#)
        - [ ] Ajouter les personnes concernées à la caption (@)

  - type: textarea
    attributes:
      label: Publication sur les réseaux sociaux
      value: |
        > Seuls les publications sur Facebook sont en français 
        - [ ] Publier visuel 1 sur Instagram, Facebook, Linkedin et Twitter
        - [ ] Publier visuel 2 sur Instagram, Facebook, Linkedin et Twitter
        - [ ] Publier visuel 3 sur Instagram, Facebook, Linkedin et Twitter
        - [ ] Publier visuel 4 sur Instagram, Facebook, Linkedin et Twitter (au besoin) 
        - [ ] Publier visuel 5 sur Instagram, Facebook, Linkedin et Twitter (au besoin)



# ---
# name: News
# about: Communication template (for single posts or weekly campaigns)
# ---
# # Description du projet
# Décrire le projet içi.

# # Création du presskit
# - [ ] Action: Créer un dossier [ici](https://github.com/CUPUM/communication/tree/main/press_kits) selon cette nomenclature : aaaammjj-press_kit-noms-news_title
# - [ ] Action: Créer le communiqué de presse en FR selon le [template](https://github.com/CUPUM/communication/blob/main/templates/press_release/wulff-template-press_release_fr-20211228.docx) ou en EN selon le [template](https://github.com/CUPUM/communication/blob/main/templates/press_release/wulff-template-press_release_en-20211228.docx) et le déposer dans le dossier
# - [ ] Action: Tag @sjinko pour valider le communiqué
# - [ ] Action: Tranduire le communiqué (FR > EN ou EN > FR)
# - [ ] Action: Mettre les communiquées (FR et EN) en ligne sur le site web
# - [ ] Action: Commenter '@sjinko, à qui envoyer ce communiqué?' 

# # Types de posts
# > Pour une campagne : Min 3 posts - Max 5 posts

# - [ ] News 
# - [ ] Photo
# - [ ] Vidéo
# - [ ] Quote
# - [ ] Conférence

# # Production des visuels
# > Des images gratuites et libres de droit se trouvent [içi](https://unsplash.com)  
# > La charte graphique de la chaire se trouve [içi](https://github.com/CUPUM/communication/blob/main/templates/CHAIRE_UNESCO_PaysageUrbain_chartegraphique.pdf)

# - [ ] Créer un dossier [ici](https://github.com/CUPUM/communication/tree/main/visuals) selon cette nomenclature : aaaammjj-projet
# - [ ] Produire le(s) visuels en anglais selon le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post) adapté 
# - [ ] Produire le(s) visuels en français selon le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post) adapté 
# - [ ] Déposer le(s) visuel(s) dans le dossier selon la nomenclature : nom-projet-aaaammjj

# # Production des captions 
# - [ ] Créer un texte pour le(s) visuel(s) à partir du presskit en utilisant le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post)
# - [ ] Ajouter les hashtags à la caption (#)
# - [ ] Ajouter les personnes concernées à la caption (@)

# # Publication sur les réseaux sociaux
#  > Seuls les posts sur Facebook sont en français 

# - [ ] Publier visuel 1 sur Instagram, Facebook, Linkedin et Twitter
# - [ ] Publier visuel 2 sur Instagram, Facebook, Linkedin et Twitter
# - [ ] Publier visuel 3 sur Instagram, Facebook, Linkedin et Twitter
# - [ ] Publier visuel 4 sur Instagram, Facebook, Linkedin et Twitter (au besoin) 
# - [ ] Publier visuel 5 sur Instagram, Facebook, Linkedin et Twitter (au besoin) 
