name: Reimbursement claim
description: "Manage the demand, claim, and reimbursement of expenses by the UNESCO Chair to individuals."
title: "Reimbursement claim: [name] for [Expense type] made for [Reason] in [Date(s)]"
assignees:
  - "sjinko"
projects:
  - "CUPUM/33"
  - "CUPUM/145"
body:
  - type: markdown
    attributes:
      value: |
        ## General
        This template manages the demand, claim, and reimbursement of expenses by UNESCO to students, collaborators, members, and external grantees. The claims follow the University's internal guidelines and regulations regarding reimbursements.

  - type: input
    id: name
    attributes:
      label: Name of grantee
      description: Enter the name of the person making the demand for reimbursement.
      placeholder: Name (e.g. First Last)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Expense type
      options:
        - Travel
        - Equipment
        - Stationary
        - Representation
        - Reception
        - Transport (taxi, local car rental)
        - Other
    validations:
      required: true

  - type: input
    attributes:
      label: Reason for expense
      description: Activity, event, and/or project associated with the expense
    validations:
      required: true

  - type: input
    attributes:
      label: Expected total amount
      description: Indicate the expected or actual amount of the expense in CAD
    validations:
      required: true

  - type: input
    attributes:
      label: Start date
      description: First day of the expense period or purchase date
    validations:
      required:
