name: Purchase
description: "Manages the purchase and utilization of goods and services."
title: "Purchase: [Type] [Quantity] [Product name] from [Vendor] for [User(s)] on [Purchase date]"
assignees:
  - sjinko
projects:
  - "CUPUM/33"
  - "CUPUM/145"
body:

- type: markdown
  attributes:
    value: |
      ## Purchasing process

      This issue concerns a purchase and acquisitions made by the UNESCO Chair in Urban Landscape. 
      
      This includes consumable and durable products and services:
      - Consumable:
        - Office supplies
        - Food and drinks
        - Subscriptions
      - Durable:
        - Books
        - Software
        - Equipment
        - Furniture
        - Other
      
      Use ONE issue per product/service/bundle (the markdown content can be copy-pasted on blank issues).

- type: dropdown
  attributes:
    label: "What is the type of purchase"
    options:
      - Office supplies
      - Food and drinks
      - Subscription
      - Book
      - Software
      - Equipment
      - Furniture
      - Other
  validations:
    required: true

- type: input
  attributes:
    label: "Quantity"
    description: "How many units are in the product/service (e.g., items, hours, counts, etc.)."
  validations:
    required: true

- type: input
  attributes:
    label: "Product name"
    description: "Give precise name, model, and version of the purchased product or service."
  validations:
    required: true

- type: input
  attributes:
    label: "Product brand"
    description: "Who produces this product or service, put 'TBD' if unknown."
  validations:
    required: true

- type: input
  attributes:
    label: "Vendor"
    description: "Company name selling the product or service, put 'TBD' if unknown."
  validations:
    required: true

- type: input
  attributes:
    label: "User(s)"
    description: "Who will be using this product or service, put 'All' if for everyone."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Reason for purchase"
    description: "Explain the motivation and context for which this purchase is made."
  validations:
    required: true

- type: input
  attributes:
    label: "Price"
    description: "Indicate the actual or estimated total price for all items including taxes."
  validations:
    required: true

- type: input
  attributes:
    label: "Project code"
    description: "Specify which financial project has been used, put 'Pending' if unknown."
  validations:
    required: true

- type: input
  attributes:
    label: "Receipt"
    description: "Drop purchase receipt when available"
  validations:
    required: false

- type: input
  attributes:
    label: "Serial or license number"
    description: "Input serial number or license number after reception, put 'Pending' if not received or 'NA' if not applicable."
  validations:
    required: true

- type: input
  attributes:
    label: "Location"
    description: "Room number, equipment or URL, put 'TBD' if unknown."
  validations:
    required: true

- type: input
  attributes:
    label: "Photo"
    description: "Drop photo of purchased items or screenshot for online"
  validations:
    required: false

- type: checkboxes
  attributes:
    label: "List of actions"
    description: "Please complete in order"
    options:
      - label: "Action: Confirm purchase with Chairholder"
      - label: "Action: Make purchase"
      - label: "Action: Create a 'Reimbursement claim' if paid by chairmember"
      - label: "Action: Drop payment receipt in issue main box"
      - label: "Action: Forward payment receipt to admins"
      - label: "Action: Receive purchase"
      - label: "Action: Add serial or licence number (if applicable)"
      - label: "Action: Ask Chairholder to specify financial project"
      - label: "Action: Add any updates (lost, broken, stolen, transfer) in comments"

- type: markdown
  attributes:
    value: |
      ### List of users/borrowers
      - [ ] Task: Borrowed by [name] on [start date] until [end date]
      - [ ] Task: Borrowed by [name] on [start date] until [end date]
