name: Event
description: This template manages the organization of events by the UNESCO Chair in Urban Landscape.
title: "Event: [Type] with [Guest(s)] at [Location] on [Date]"
assignees: []
projects: ["CUPUM/148"]

body:
  - type: markdown
    attributes:
      value: |
        ### General
        This template manages the organization of events by the UNESCO Chair in Urban Landscape.

        The organization is divided into three phases:

        1. Pre-event  
        2. Event  
        3. Post-event

  - type: markdown
    attributes:
      value: |
        ### Event information

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the type of event.
      options:
        - Conference
        - Seminar
        - Exhibition
        - Launch
        - Networking
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Specify where the workshop takes place. e.g. "Hall de la Faculté de l'aménagement", "4133", "Teams"
      placeholder: Faculté de l'aménagement, 4133, Teams...

  - type: input
    id: datetime
    attributes:
      label: Date and time
      description: Indicate when the workshop takes place. e.g. `2025-01-01 06:15`
      placeholder: YYYY-MM-DD HH:MM

  - type: input
    id: host
    attributes:
      label: Host
      description: Specify who is hosting the event. The host is not necessarily the organizer.
      placeholder: e.g. Shin Koseki
    validations:
      required: true

  - type: textarea
    id: guests
    attributes:
      label: Guest(s)
      description: Specify who the guest(s) of the event are.
      placeholder: e.g. Carmella Cucuzzella, Valérie Plante
    validations:
      required: true

  - type: textarea
    id: attendees
    attributes:
      label: Attendees
      description: Specify who is attending the event.
      placeholder: e.g. CUPUM members, UNESCO Studio students, UdeM community
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Tasks
        Not all tasks apply to every event. Please select the ones relevant to this event.

  - type: checkboxes
    id: pre_event_tasks
    attributes:
      label: Pre-event tasks
      options:
        - label: "Task: Book a guest"
        - label: "Task: Create online event"
        - label: "Task: Reserve room"
        - label: "Task: Order furniture"
        - label: "Task: Order audiovisual equipment"
        - label: "Task: Order food and drinks"
        - label: "Task: Obtain authorization from Direction de la prévention et de la sécurité"
        - label: "Task: Obtain alcohol permit"
        - label: "Task: Hire internal team"
        - label: "Task: Hire professionals (photographer, DJ, circus artist)"
        - label: "Task: Invite attendees"

  - type: checkboxes
    id: event_tasks
    attributes:
      label: Event tasks
      options:
        - label: "Task: Set up space"
        - label: "Task: Welcome people"
        - label: "Task: Take pictures"
        - label: "Task: Take notes"
        - label: "Task: Dismantle space"

  - type: checkboxes
    id: post_event_tasks
    attributes:
      label: Post-event tasks
      options:
        - label: "Task: Return equipment"
        - label: "Task: Write back to the guest(s)"
        - label: "Task: Write back to attendees"
        - label: "Task: Create a news issue to cover the event"

  - type: markdown
    attributes:
      value: |
        ### List of actions

  - type: checkboxes
    id: list_of_actions
    attributes:
      label: Actions
      options:
        - label: "Action: Name issue according to template format"
        - label: "Action: Assign issue to event organizer"
        - label: "Action: Add related project to issue"
        - label: "Action: Add beginning and end dates to the issue"
