name: Event Organization
description: Template to organize an event with phases and checklist.
title: "Event: [Type] with [Participants] at [Location] on [Date]"
labels: event
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### General
        The organization of an event usually includes four phases: obtaining authorizations (if needed), logistics, invitations, and communication.

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the type of event.
      options:
        - label: Conference
        - label: Exhibition
        - label: Launch
        - label: Networking
    validations:
      required: true

  - type: input
    id: participants
    attributes:
      label: Participants
      description: Specify the participants.
      placeholder: e.g. CUPUM members, Faculty members, community members
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Specify where the event takes place (e.g., "Faculté de l'aménagement", "Zoom", "Teams").
      placeholder: Location
    validations:
      required: true

  - type: input
    id: datetime
    attributes:
      label: Date and time
      description: Indicate when the event takes place (e.g., 2025-06-01 06:15).
      placeholder: YYYY-MM-DD HH:mm
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Authorisations
        In-person events often require a reservation for the space to be used. Reservation needs to be made with the entity responsable for the space, e.g.: CUPUM, School of Urban Planning and Landscape Architedcture, Faculty of Environemental Design or Direction des immeubles. See contact list for details. 

  - type: checkboxes
    id: authorisations
    attributes:
      label: Authorisations checklist
      options:
        - label: Request a reservation
        - label: Request authorization from Direction de la prévention et de la sécurité (for DI space only)
        - label: Obtain an alcohol permit

  - type: markdown
    attributes:
      value: |
        ### Logistics

  - type: checkboxes
    id: logistics
    attributes:
      label: Logistics checklist
      options:
        - label: Prepare audiovisual material
        - label: Prepare drinks and/or beverages for participants

  - type: markdown
    attributes:
      value: |
        ### Invitations
        For internal events, calendar invitations can be used. For events with a wider audience, use a platform such as Eventbrite.

  - type: checkboxes
    id: invitations
    attributes:
      label: Invitations checklist
      options:
        - label: Create guestlist
        - label: Send invitations

  - type: markdown
    attributes:
      value: |
        ### Communication

  - type: checkboxes
    id: communication
    attributes:
      label: Communication checklist
      options:
        - label: Create an issue news to announce the event
        - label: Create an issue news to cover the event
        - label: Contact the communication advisor at the Faculty of Environmental Design for diffusion within the Faculty
        - label: Contact the communication advisor at the University of Montreal for diffusion with UdeM
        - label: Contact the edition technician for UdeM TV diffusion
