name: Event Organization
description: This template manages the organization of events by the UNESCO Chair in Urban Landscape.
title: "Event: [Type] with [Guest(s)] at [Location] on [Date]"
labels: event
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ### General
        This template manages the organization of events by the UNESCO Chair in Urban Landscape.

        The organization is divided into three phases:

        1. Pre-event  
        2. Event  
        3. Post-event

  - type: markdown
    attributes:
      value: |
        ### Event information

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Select the type of event.
      options:
        - label: Conference
        - label: Seminar
        - label: Exhibition
        - label: Launch
        - label: Networking
    validations:
      required: true

  - type: textarea
    id: host
    attributes:
      label: Host
      description: Specify who is hosting the event. The host is not necessarily the organizer.
      placeholder: e.g. Shin Koseki
    validations:
      required: true

  - type: textarea
    id: guests
    attributes:
      label: Guest(s)
      description: Specify who the guest(s) of the event are.
      placeholder: e.g. Carmella Cucuzzella, Valérie Plante
    validations:
      required: true

  - type: textarea
    id: attendees
    attributes:
      label: Attendees
      description: Specify who is attending the event.
      placeholder: e.g. CUPUM members, UNESCO Studio students, UdeM community
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Pre-event tasks  
        Not all tasks apply to every event. Please select the ones relevant to this event.

  - type: checkboxes
    id: pre_event_tasks
    attributes:
      label: Pre-event tasks
      options:
        - label: Book a guest
        - label: Create online event
        - label: Reserve room
        - label: Order furniture
        - label: Order audiovisual equipment
        - label: Order food and drinks
        - label: Obtain authorization from Direction de la prévention et de la sécurité
        - label: Obtain alcohol permit
        - label: Hire internal team
        - label: Hire professionals (photographer, DJ, circus artist)
        - label: Invite attendees

  - type: markdown
    attributes:
      value: |
        ### Event

  - type: checkboxes
    id: event_tasks
    attributes:
      label: Event tasks
      options:
        - label: Set up space
        - label: Welcome people
        - label: Take pictures
        - label: Take notes
        - label: Dismantle space

  - type: markdown
    attributes:
      value: |
        ### Post-event

  - type: checkboxes
    id: post_event_tasks
    attributes:
      label: Post-event tasks
      options:
        - label: Return equipment
        - label: Write back to the guest(s)
        - label: Write back to attendees
        - label: Create a news issue to cover the event

  - type: markdown
    attributes:
      value: |
        ### List of actions

  - type: checkboxes
    id: list_of_actions
    attributes:
      label: Actions
      options:
        - label: Name issue according to template format
        - label: Assign issue to event organizer
        - label: Add related project to issue
        - label: Add beginning and end dates to the issue
