name: Onboarding
description: "Streamline the onboarding of a new chair member or collaborator."
title: "Onboarding: [First] [Last] as new [Role] starting on [Start date]"
assignees: ["delphineduplain"]
projet: projects: ["CUPUM/33", "CUPUM/145"]
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      ## General
      
      This template manages the onboarding of new collaborators upon their arrival at the UNESCO Chair in Urban Landscape. 

      ## Roles

      The unbording of new collaborators involves the following people:

      - The Chairholder
      - The Project coordinator (who will oversee the Onboardee’s work)
      - The Onboarder
      - The Onboardee 

      ## Description 
      The onboarding aims to ease the rapid and seamless integration to new comers at the UNESCO Chair through three phases:

      1. Pre arrival
      2. Arrival
      3. Post arrival

      Each phases serves a specific purpose and should be completed deligently.
      
      
- type: input
  id: first_name
  attributes:
    label: First name
  validations:
    required: true

- type: input
  id: last_name
  attribues:
    label: Last name
  validations:
    required: true

- type: dropdown
  id: role
  attributes:
    label: What role for this new person
    multiple: true
    options:
      - New student
      - New employee
      - New intern
      - New guest
      - Other
   validations:
     required: true

- type: input
  id: start_date
  attributes:
    label: First day at the UNESCO Chair (onboarding day)
    placeholder: yyyy-mm-dd
  validations:
    required: true

- type: checkboxes
  id: pre_arrival
  attributes:
    label: Pre arrival actions  
    description: Four to two week before the Onboardee arrival date. 
    options:
      - label: Action: Schedule a 30-minute onboarding meeting with Chairholder on Starting date
      - label: Action: Schedule a one-hour onboarding meeting with the Project lead on Starting date
      - label: Action: Schedule a one-hour introduction to GitHub with team memebr on Starting date
      - label: Action: Schedule a onboarding tea or lunch with chair members on Starting date
      - label: Action: Email Onboardee, Chairholder and Project coordinator to share information and request actions (use email templates below)
      - label: Action: Add onboardee to all events and event series listed in email
      - label: Action: Request key using a Key attribution issue
      - label: Action: For non-UdeM Onboardee, create a SIM Account to access UdeM online systems (requires birth date and full name)
      - label: Action: Add Onboardee to relevant calendar events (project and social)  
      - label: Action: Once GitHub personal account set up, add Onboardee to UNESCO Chair’s organization GitHub Account and teams
      - label: Action: Add Onboardee to Slack

      ´´´
      Dear [First name],

      In prevision to your arrival to the UNESCO Chair in Urban Landscape, please take the time to read the followin email and complete the listed actions at least one week before your starting date.

      **Starting day**
      Your first day at the UNESCO Chair is planned as follow:
      - HH.MM to HH.MM — Welcome meeting with Shin Koseki
      - HH.MM to HH.MM — Project onboarding meeting with [Project coordinator]
      - HH.MM to HH.MM — GitHub introduction session with [Designated chair member]
      - HH.MM to HH.MM — Welcoming [tea/lunch] with members of the UNESCO Chair

      **Upcoming events**
      As part of your affiliation at the UNESCO Chair, you are invited to attend the following reccuring meetings:
      - Project meeting series 1
      - Project meeting series 2
      - ...

      Here are also some additional social events we are looking forward to seeing you at:
      - Chaire sociale event 1
      - Chaire sociale event 2
      - ...
      
      Calendar invitations for these events will follow.

      **Required actions**
      1. Create an account on GitHub using your UdeM email address
      2. Create an account on Slack using your UdeM email address
      3. Email us back your full name and date of birth. This is required to create an UdeM digital access code (SIM).

      ´´´
      
- type: checkboxes
  id: actions_priors
  attribued:
    label: To complete before start date
    description: Check or activate as issue in General repo
    options:
      - label: Task: Email [First Name] as new [Role] about onboarding process
      - label: [Key attribution: [Key code] to [Borrower’s name] to access [Access type] [Room number]](https://github.com/CUPUM/general/issues/new?template=09-key_issue.yml)


- type: textarea
  id: email_onboardee
  attributes:
    label: Email to onboardee prior to arrival
    description: "Send minimum one week before arrival to UNESCO Chair"
    value: |
      Bonjour,

      En prévision de votre arrivé à la Chaire UNESCO en paysage urbain, nous vous invitons à compléter les étapes suivantes avant votre première journée:
      1. [Créer un compte SIM temporaire](https://ti.umontreal.ca/formulaires/formulaire-de-demande-pour-les-services-client-unite/) (si vous n’être pas affilié à l’Université de Montraél) 
      
      ([See additionnal information here])
      2. Créer un compte sur https://github.com avec votre adresse de l’Université de Montréal, si vous n’avez pas encore de compte GitHub ; 
      3. 

    render: bash
    validations:
      required: true


      
- type: textarea
  attributes:
    label: Project teams
    description: |
      List the teams for which the onboardee should gain access to work on their assigned projects.
      You can find a list of the organisation's teams [here](https://github.com/orgs/CUPUM/teams).
    placeholder: |
      - [ ] ...

- type: textarea
  attributes:
    label: List of actions for chair staff
    value: |
      - [ ] [Invite onboardee to the organization](https://github.com/orgs/CUPUM/people)
      - [ ] [Add onboardee to relevant team(s)](https://github.com/orgs/CUPUM/teams)
      - [ ] Schedule an onboarding meeting with the arriving collaborator
      - [ ] @delphineduplain: Schedule an introduction meeting with the arriving collaborator
      - [ ] @team: Schedule an introduction meeting with the arriving collaborator
      - [ ] @team: Make sure the onboardee is added to the list of invited people the relevant calendar events

- type: textarea
  attributes:
    label: To do for arriving collaborator
    description: "List the steps to complete in order to fully onboard the new member once they have arrived."
    value: |
      - [ ] Register on GitHub
      - [ ] Skim through the documentation on [Getting started with GitHub](https://docs.github.com/en/get-started/onboarding/getting-started-with-your-github-account)
      - [ ] 🎉 Open your first issue! 🎉
