name: Onboarding
description: "Streamline the onboarding of a new chair member or collaborator."
title: "Onboarding: [First] [Last] as new [Role] starting on [Start date]"
assignees: ["delphineduplain"]
projects: ["CUPUM/33", "CUPUM/145"]
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      ## General
      
      This template manages the onboarding of new collaborators upon their arrival at the UNESCO Chair in Urban Landscape.
      
      The onboarding aims to ensure a smooth integration for newcomers at the UNESCO Chair through three phases:

      1. Pre-arrival
      2. Arrival
      3. Post-arrival

      Each phase serves a specific purpose and should be completed diligently.
      
      ## Roles

      The onboarding of new collaborators involves the following people:

      - The Chairholder
      - The Project Coordinator (who will oversee the Onboardee’s work)
      - The Onboarder (who is responsible to process the onboarding task)
      - The Onboardee (new comer)

- type: markdown
  attributes:
    value: |
      ## Onboardee information

- type: input
  id: first_name
  attributes:
    label: First name
  validations:
    required: true

- type: input
  id: last_name
  attributes:
    label: Last name
  validations:
    required: true

- type: dropdown
  id: role
  attributes:
    label: What role(s) is this new person taking?
    multiple: true
    options:
      - New student
      - New employee
      - New intern
      - New guest
      - Other
  validations:
    required: true

- type: input
  id: start_date
  attributes:
    label: Start date at the UNESCO Chair
    placeholder: yyyy-mm-dd
  validations:
    required: true

- type: markdown
  id: resources
  attributes:
    value: |
      ## 1. Pre-arrival
    
      ### Information and resources

      #### SIM Account
      The SIM account is required to access digital services at the University of Montreal (WiFi, library, MonUdeM, Syncho, etc.). It is _de facto_ the University’s digital identity credentials.
      
      #### Pre-arrival email template

      ```
      Dear [First name],

      In preparation for your arrival at the UNESCO Chair in Urban Landscape, please take the time to read the following email and complete the listed actions at least one week before your starting date.

      **Starting Day Schedule**
      Your first day at the UNESCO Chair is planned as follows:
      - HH:MM – HH:MM — Welcome meeting with Shin Koseki
      - HH:MM – HH:MM — Project onboarding meeting with [Project Coordinator]
      - HH:MM – HH:MM — GitHub introduction session with [Designated Chair Member]
      - HH:MM – HH:MM — Welcoming [tea/lunch] with members of the UNESCO Chair

      **Upcoming Events**
      As part of your affiliation with the UNESCO Chair, you are invited to attend the following recurring meetings:
      - Project meeting series 1
      - Project meeting series 2
      - ...

      Additionally, here are some upcoming social events where we look forward to seeing you:
      - Chair social event 1
      - Chair social event 2
      - ...

      Electronic calendar invitations for these events will follow.

      **Required Actions**
      1. Create an account on https://github.com/ using your @umontreal.ca email address (unless you already have an account).
      2. Create an account on Slack using your @umontreal.ca email address.
      3. Email us back your date of birth. This is required to create your UdeM digital access code (SIM).

      Best regards,  
      [Onboarder]
      ```

- type: checkboxes
  id: pre_arrival_actions
  attributes:
    label: Pre-arrival actions  
    description: Two to four weeks before the Onboardee’s start date.  
    options:
      - label: Schedule a 30-minute onboarding meeting with Chairholder on Starting Date (use issue comments)
      - label: Schedule a one-hour onboarding meeting with the Project Lead on Starting Date (use issue comments)
      - label: Schedule a one-hour introduction to GitHub with a team member on Starting Date (use issue comments)
      - label: Schedule an onboarding tea or lunch with chair members on Starting Date (create a calendar invite)
      - label: Email Onboardee information and request actions, cc Chairholder and Project Coordinator (use template above)
      - label: Add Onboardee to all events and event series listed in email 
      - label: Request a key to access office space (use the [Key Attribution Issue Template](https://github.com/CUPUM/general/issues/new?template=09-key_issue.yml))
      - label: For non-UdeM Onboardees, create a SIM Account to access UdeM online systems (use link above)
      - label: Once GitHub personal account is set up, add Onboardee to the UNESCO Chair’s organization GitHub account and teams
      - label: Ask Slack account administrators to add Onboardee to Slack (use issue comments)
