name: Task form
description: Create a new task (potentially under an epic)
body:
  - type: markdown
    attributes:
      value: |
        Fill out the following form to create a new task
  - type: textarea
    attributes:
      label: "Task description"
      description: "Provide an overview of the task."
      placeholder: "Describe the task..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actions"
      description: "Decline a list of actions to complete the task."
      placeholder: "- [ ] Action..."
    validations:
      required: false
