name: Task v2
title: "Task: "
description: "Create a new task to describe and assign work. Tasks can list or link other tasks, but should ultimately contain work of their own. Please use projects in lieu of epics."
body:
  - type: textarea
    attributes:
      label: Description
      value: "## Task description"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Work / steps to complete"
      value: |
      "## To do"
      "- ..."
    validations:
      required: true
