name: Task v2
title: "Task: "
description: "Create a new task to describe and assign work. Tasks can list or link other tasks, but should ultimately contain work of their own. Please use projects in lieu of epics."
body:
  - type: textarea
    attributes:
      label: Description
      description: "Provide a broad description of the work to be done. Don't skimp on linking to other issues to help contextualize readers."
    validations:
      required: true
  - type: textarea
    attributes:
      label: To do
      description:  "Specify at least one action to do to progress this issue. You can append new actions as the work better defines itself through feedback."
      value: |
        - [ ] ...
    validations:
      required: true
