name: Epic v2
description: "Complex sets of tasks"
title: "Epic: "
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      Epics issues serve to manage and track complex sets of tasks. They are managed by one assignee who organizes, documents, tracks and closes the epic. To create an epic:
      1. Name the epic clearly by stating what will be achieverd using an action verb the details
      Eg. *"Epic: Publish 'AI & Cities' paper in *Nature* by Oct. 1"*
      2. Assign **one** person. The epic assignee is responsible to coordinate listed tasks and deliver the epic on time
      3. Add to relevant projects. Project managers are responsible to coordinate epics and deliver projects on time 

# Epic description
- type: textarea
  attributes:
    label: Epic description
    description: Clearly describe the 'why', 'how' and 'what' of the epic
    placeholder: This epic serves to ...

# List of tasks
- type: textarea
  attributes:
    label: List of tasks
    description: |
      List tasks required to complete the epic. Tasks can be listed then created as issues or linked using url or \#
    placeholder: |
      - [ ] Task: name of tasks
      - [ ] Task: #n (if in the same repo)

