name: Epic v2
description: "Complex sets of tasks"
title: "Epic: "
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      Epics issues serve to manage and track complex sets of tasks. 
      The title should clearly state the goal of the epic with an action verb the deadline
      Eg. *"Publish 'AI & Cities' paper in *Nature* by Oct. 1"*
      There should be **only one person assigned** at the time 
      The assignee is responsible to coordinate listed tasks and deliver the epic in time

# Epic description
  - type: textarea
    attributes:
      label: Epic description
      description: Describe what should be achieved and how
      placeholder: This epic serves to ...

# List of tasks
  - type: textarea
    attributes:
      label: List of tasks
      description: |
        List tasks required to complete the epic. Tasks can be listed then created as issues or linked using url or #
      placeholder: |
        - [ ] Task: *name of tasks"
        - [ ] Task: *#n* (if in the same repo)

