name: Meeting
description: "Create and track a meeting."
title: "Meeting: "
body:
  - type: input
    attributes:
      label: Event or invite link
      description: Add a link to a relevant calendar event that people can refer to in order to track the date & time and outside attendees.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ### Attendees
        Append any attending or invited team members to this issue's list of assignees.
  - type: textarea
    attributes:
      label: Reported points
      description: Synthesize relevant past meeting discussion points or link to prefacing issues.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Order of the day
      description: Plan points to discuss in chronological order. Optionally tag people associated to each points or groups of points.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minutes
      value: "_(Add meeting notes here)_"
      description: "Use this section to take meeting notes or synthesize attendees' notes after the issue has been created."
    validations:
      required: false
