name: Meeting
description: "Plan, organize and record meetings"
title: "Meet: "
body:

  
- type: textarea
  attributes:
    label: Meeting notes
    description: Based on the agenda, summarize key information, decisions and resources 
    placeholder: |
      **Topic 1**
      - ...
      - ...
