name: Meeting
description: "Plan, organize and record meetings"
title: "Meet: "
body:

- type: markdown
  attributes:
    value: |
      Meeting issues serve to plan, organize, record and follow up on all meetings conducted. The title of the meeting issue should specify mode, persons and date of the meeting: *e.g. “Meet: Phone call with Martin Duchamp and Carine Genou about PublicSpace.AI on Jan. 23”*

#- type: markdown
#  attribute: 
#    value: "For Chair participants, add as issue assignees -->"

#- type: textarea
#  attribute:
#    label: External participants
#    description: List full names and affiliation of non-chair participants to the meeting
#    placeholder: |
#     - Carine Genou (Ville de Laval)
#      - Martin Duchamp (Ville de Montréal)
#    value: "TBD"

- type: input
  attributes:
    label: Location
    description: Specify where the meeting takes place. e.g. “Faculté de l’aménagement”, “Zoom”, ”Phone", ”UNESCO HQ“
    placeholder: Phone/Zoom/Teams/Building...
    value: "TBD"

- type: input
  attributes:
    label: Date and time
    description: Indicate when the meeting take place. e.g. `2024-12-31 22:05`
    placeholder: YYYY-MM-DD HH:MM
    value: "TBD"

- type: textarea
  attributes:
    label: Meeting description
    description: Describe the objective, context and key information
    placeholder: This meeting serves to ...

- type: textarea
  attributes:
    label: Meeting agendy
    description: Describe the objective, context and key information
    value: "TBD"
  
- type: textarea
  attributes:
    label: Meeting notes
    description: Based on the agenda, summarize key information, decisions and resources 
    placeholder: |
      **Topic 1**
      - ...
      - ...
