name: Meeting
description: "Plan, organize, record and follow up on meetings"
title: "Meet: "
body:

- type: markdown
  attributes:
    value: |
      Meeting issues serve to plan, organize, record and follow up on internal and external meetings. 
      The title of the meeting issue should specify mode, persons and date of the meeting:
      *e.g. “Meet: Phone call with Martin Duchamp and Carine Genou about PublicSpace.AI on Jan. 23”*

- type: markdown
  attributes: 
    value: **Assign this issue to all people participating to the meeting**"

- type: textarea
  attributes:
    label: External participants
    description: List full names and affiliation of non-chair participants to the meeting
    placeholder: |
     - Carine Genou (Ville de Laval)
     - Martin Duchamp (Ville de Montréal)

- type: input
  attributes:
    label: Location
    description: Specify where the meeting takes place. e.g. “Faculté de l’aménagement”, “Zoom”, ”Phone", ”UNESCO HQ“
    placeholder: Phone/Zoom/Teams/Building...

- type: input
  attributes:
    label: Date and time
    description: Indicate when the meeting take place. e.g. `2024-12-31 22:05`
    placeholder: YYYY-MM-DD HH:MM

- type: textarea
  attributes:
    label: Meeting description
    description: Describe the objective, context and key information
    placeholder: This meeting serves to ...

- type: textarea
  attributes:
    label: Meeting agenda
    description: Describe the objective, context and key information
    placeholder: "TBD"

- type: textarea
  attributes:
    label: Meeting notes
    description: Based on the agenda, summarize key information, decisions and resources 
    value: |
      - ...
      - ...
   
- type: textarea
  attributes:
    label: Actionable items
    description: List actions to turn into issues
    value: |
      - [ ] Task: ...
      - [ ] Task: ...
      - [ ] Task: ...

- type: textarea
  attributes:
    label: List of actions
    descrpition: Actions to organize meeting
    value: |
      - [ ] Action: Schedule meeting
      - [ ] Action: Define meeting agenda
      - [ ] Action: Hold meeting and take notes
      - [ ] Action: Convert actionable items to issues
      - [ ] Action: Write back to guest(s) with next steps
