name: News
description: "Communication template (for single posts or weekly campaigns)."
title: "News: "
body:

  - type: markdown
    attributes:
      value: |
        Epics should have a title that doesn't simply reiterate what its contained tasks already state.
        It should summarize the scope of work.

        Make sure to assign your epic to a project.

  - type: textarea
    attributes:
      label: Presskit preparation
      description: Prepare all the material necessary for publishing across the chair's platforms.
    validations:
      required: false

  - type: textarea
    attributes:
      label: List of tasks
      description: |
        List all the tasks required to complete this epic, preferably in logical order of priority.
        Remember that you can use `#...` to link to existing tasks and automatically track their progress within this list. 
      value: |
        - [ ] Task: TBD
    validations:
      required: false



# ---
# name: News
# about: Communication template (for single posts or weekly campaigns)
# ---
# # Description du projet
# Décrire le projet içi.

# # Création du presskit
# - [ ] Action: Créer un dossier [ici](https://github.com/CUPUM/communication/tree/main/press_kits) selon cette nomenclature : aaaammjj-press_kit-noms-news_title
# - [ ] Action: Créer le communiqué de presse en FR selon le [template](https://github.com/CUPUM/communication/blob/main/templates/press_release/wulff-template-press_release_fr-20211228.docx) ou en EN selon le [template](https://github.com/CUPUM/communication/blob/main/templates/press_release/wulff-template-press_release_en-20211228.docx) et le déposer dans le dossier
# - [ ] Action: Tag @sjinko pour valider le communiqué
# - [ ] Action: Tranduire le communiqué (FR > EN ou EN > FR)
# - [ ] Action: Mettre les communiquées (FR et EN) en ligne sur le site web
# - [ ] Action: Commenter '@sjinko, à qui envoyer ce communiqué?' 

# # Types de posts
# > Pour une campagne : Min 3 posts - Max 5 posts

# - [ ] News 
# - [ ] Photo
# - [ ] Vidéo
# - [ ] Quote
# - [ ] Conférence

# # Production des visuels
# > Des images gratuites et libres de droit se trouvent [içi](https://unsplash.com)  
# > La charte graphique de la chaire se trouve [içi](https://github.com/CUPUM/communication/blob/main/templates/CHAIRE_UNESCO_PaysageUrbain_chartegraphique.pdf)

# - [ ] Créer un dossier [ici](https://github.com/CUPUM/communication/tree/main/visuals) selon cette nomenclature : aaaammjj-projet
# - [ ] Produire le(s) visuels en anglais selon le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post) adapté 
# - [ ] Produire le(s) visuels en français selon le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post) adapté 
# - [ ] Déposer le(s) visuel(s) dans le dossier selon la nomenclature : nom-projet-aaaammjj

# # Production des captions 
# - [ ] Créer un texte pour le(s) visuel(s) à partir du presskit en utilisant le [template](https://github.com/CUPUM/communication/tree/main/templates/social_media_post)
# - [ ] Ajouter les hashtags à la caption (#)
# - [ ] Ajouter les personnes concernées à la caption (@)

# # Publication sur les réseaux sociaux
#  > Seuls les posts sur Facebook sont en français 

# - [ ] Publier visuel 1 sur Instagram, Facebook, Linkedin et Twitter
# - [ ] Publier visuel 2 sur Instagram, Facebook, Linkedin et Twitter
# - [ ] Publier visuel 3 sur Instagram, Facebook, Linkedin et Twitter
# - [ ] Publier visuel 4 sur Instagram, Facebook, Linkedin et Twitter (au besoin) 
# - [ ] Publier visuel 5 sur Instagram, Facebook, Linkedin et Twitter (au besoin) 
