name: Onboarding
description: |
  Streamline onboarding of new members or collaborators.
title: "Onboarding: N. Last Name"
body:

  - type: markdown
    attributes:
      value: |
        Onboarding refers to the introduction of a new member or collaborator to the chair's activity's and platforms.
        
        Give an adequate name to your onboarding issue. The title of this issue should follow the format `Onboarding: [First name] [Last name]`

  - type: textarea
    attributes:
      label: Project teams
      description: |
        List the teams for which the onboardee should gain access to work on their assigned projects.
        You can find a list of the organisation's teams [here](https://github.com/orgs/CUPUM/teams).
      placeholder: |
        - [ ] ...

  - type: textarea
    attributes:
      label: List of actions for chair staff
      value: |
        - [ ] @iolyd: [Invite onboardee to the organization](https://github.com/orgs/CUPUM/people)
        - [ ] @iolyd: [Add onboardee to relevant team(s)](https://github.com/orgs/CUPUM/teams)
        - [ ] @iolyd: Request temporary invited collaborator Wi-Fi access
        - [ ] @iolyd: Schedule an onboarding meeting with the arriving collaborator
        - [ ] @delphineduplain: Schedule an onboarding meeting with the arriving collaborator
        - [ ] Coordinating team member: Schedule an onboarding meeting with the arriving collaborator

  - type: textarea
    attributes:
      label: To do for arriving collaborator
      description: "List the steps to complete in order to fully onboard the new member once they have arrived."
      value: |
        - [ ] Register on GitHub
        - [ ] Skim through the documentation on [Getting started with GitHub](https://docs.github.com/en/get-started/onboarding/getting-started-with-your-github-account)
        - [ ] 🎉 Open your first issue! 🎉
