name: Onboarding
description: |
  Streamline the onboarding of a new chair member or collaborator.
title: "Onboarding: "
assignees:
  - delphineduplain
body:

  - type: markdown
    attributes:
      value: |
        Onboarding refers to the introduction of a new member or collaborator to the chair's activity's and platforms.

        Giving an adequate name to your onboarding issue is important to ensure proper tracking. The title should specify the onboardee's, respecting the following format:
        *“Onboarding: F. Law Olmsted"*

  - type: textarea
    attributes:
      label: Project teams
      description: |
        List the teams for which the onboardee should gain access to work on their assigned projects.
        You can find a list of the organisation's teams [here](https://github.com/orgs/CUPUM/teams).
      placeholder: |
        - [ ] ...

  - type: textarea
    attributes:
      label: List of actions for chair staff
      value: |
        - [ ] [Invite onboardee to the organization](https://github.com/orgs/CUPUM/people)
        - [ ] [Add onboardee to relevant team(s)](https://github.com/orgs/CUPUM/teams)
        - [ ] Request creation of temporary SIM account for invited collaborator using [the indicated form](https://ti.umontreal.ca/formulaires/formulaire-de-demande-pour-les-services-client-unite/) ([See additionnal information here](https://wiki.umontreal.ca/display/SIE/Compte+utilisateur))
        - [ ] Schedule an onboarding meeting with the arriving collaborator
        - [ ] @delphineduplain: Schedule an introduction meeting with the arriving collaborator
        - [ ] @team: Schedule an introduction meeting with the arriving collaborator
        - [ ] @team: Make sure the onboardee is added to the list of invited people the relevant calendar events

  - type: textarea
    attributes:
      label: To do for arriving collaborator
      description: "List the steps to complete in order to fully onboard the new member once they have arrived."
      value: |
        - [ ] Register on GitHub
        - [ ] Skim through the documentation on [Getting started with GitHub](https://docs.github.com/en/get-started/onboarding/getting-started-with-your-github-account)
        - [ ] 🎉 Open your first issue! 🎉
