name: Order form
description: Kickstart a new material order process
title: "Order: [Product name] for [purpose or end user]"
body:
  - type: markdown
    attributes:
      value: |
        # Order description
        Complete the fields below to outline the order's details and needs as well as to launch the purchase process
  - type: input
    attributes:
      label: "End user(s)"
      description: "Who is this order carried out for?"
  - type: input
    attributes:
      label: "Purpose"
      description: "What will the acquired material be used for?"
  - type: input
    attributes:
      label: "Funds"
      description: "Specify which project or funding to use for the purchase."
- type: textarea
    attributes:
      label: "Items"
      description: "Provide an exhaustive list of the items comprised in this order."
      value: |
        \| Name \| Cost <!-- Specify currency if not in CAD --> \|
       
